a = input('digite algo: ')
print(' o tipo primitivo desse valor é ', type(a))
print('Só tem espaçõs? ', a.isspace())
print('é um número? ', a.isnumeric())
print('é algabetico', a.isalpha())
print('é alfanumerico', a.isalnum())
print('está em maiusculas', a.isupper())
print('está em minuscula', a.islower())
print('está capitalizada', a.istitle())
